language: java
jdk:
- oraclejdk8
install: mvn --settings settings.xml  -DskipTests=true clean install -q
script: mvn --settings settings.xml   test
before_deploy: "./deploy.sh"
deploy:
  provider: releases
  api_key:
    secure: BgiJ0rmm1IFbOttfsoXcxisMN8Y5eJiMisMm7eJVlhGYDeRWWpRl2ZAhsm68ESuc3wbrcjQ0kxUdqFSDtzJqaFfo50wm/L0RNpSeuAu1+gaK92S3JH1obrcM1wQrVa+TB7nB4THklR0Jh4YLRNznTiPNgUXDLdhgWo43Q2fQQ3I=
  file: -limo.exe-limo.sh-limo.tgz
  on:
    tags: true
notifications:
  email:
    recipients:
    - limo@fontysvenlo.org
    on_success: change
    on_failure: always
  slack:
    secure: gfhbtlBAa0wAXpJyybz17QoVn3LAG8aR4TIEYIVoIOEr4eFSe0yyD/A6XRq4+BlVX34MQTqRURg1zxkE6A6llAC/lKeo0adXQyORnO06yY511DbPpKft43Bo/V8RWPtvbuHkkbNJ6srzsJqNCqOTbW/ko0wDQeCZYjBtPqovveo=
env:
  global:
    secure: CmFSnKFrRLuzaC3pxc+z7m2dr0c/oG/Qh5S4cIJCg4SuUHVHVM2LuXnGCE9lNdXQZtQeSLvkte2L9Yoluob4zDYTpMoMrWwMc2n5gbJLam0NLCjEZWkhl3AOSrYePBV1dZVmgPdta4301vhvM+4fDC/oTvPvsGvLqJdAMUazMxA=
