/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.limo.view.wizard;

import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

public final class AddHubWizardVisualPanel1 extends JPanel {

	/**
	 * Creates new form AddHubWizardVisualPanel1
	 */
	public AddHubWizardVisualPanel1() {
		initComponents();
	}

	@Override
	public String getName() {
		return "Name and Location";
	}

	public JComboBox getHubType(){
		return hubTypeCB;
	}

	public JTextField getHubName(){
		return hubNameTF;
	}

	public JTextField getHubLocation(){
		return hubLocationTF;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    hubTypeCB = new javax.swing.JComboBox();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    hubNameTF = new javax.swing.JTextField();
    hubLocationTF = new javax.swing.JTextField();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.jLabel1.text_1")); // NOI18N

    hubTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.jLabel2.text_1")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.jLabel3.text_1")); // NOI18N

    hubNameTF.setText(org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.hubNameTF.text")); // NOI18N

    hubLocationTF.setText(org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.hubLocationTF.text")); // NOI18N
    hubLocationTF.setToolTipText(org.openide.util.NbBundle.getMessage(AddHubWizardVisualPanel1.class, "AddHubWizardVisualPanel1.hubLocationTF.toolTipText")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(73, 73, 73)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel3)
          .addComponent(jLabel2)
          .addComponent(jLabel1))
        .addGap(38, 38, 38)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(hubTypeCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(hubNameTF)
          .addComponent(hubLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(90, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(55, 55, 55)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(hubTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(47, 47, 47)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(hubNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(52, 52, 52)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(hubLocationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(84, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField hubLocationTF;
  private javax.swing.JTextField hubNameTF;
  private javax.swing.JComboBox hubTypeCB;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
