/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.limo.view.wizard;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import nl.fontys.sofa.limo.domain.category.Category;

public final class AddHubWizardVisualPanel2 extends JPanel {
	private List<JTextField> costCategoryTFs;
	private List<JTextField> timeCategoryTFs;

	/**
	 * Creates new form AddHubWizardVisualPanel2
	 */
	public AddHubWizardVisualPanel2() {
		initComponents();
		costCategoryTFs = new ArrayList<>();
		timeCategoryTFs = new ArrayList<>();
	}

	@Override
	public String getName() {
		return "Costs and delays";
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    scrollPaneLeft = new javax.swing.JScrollPane();
    labelPanel = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    scrollPane2 = new javax.swing.JScrollPane();
    textFieldPanel = new javax.swing.JPanel();

    setBorder(javax.swing.BorderFactory.createEmptyBorder(50, 75, 25, 100));
    setMaximumSize(new java.awt.Dimension(300, 300));
    setMinimumSize(new java.awt.Dimension(100, 100));
    setPreferredSize(new java.awt.Dimension(300, 300));
    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

    scrollPaneLeft.setBorder(null);

    labelPanel.setLayout(new javax.swing.BoxLayout(labelPanel, javax.swing.BoxLayout.PAGE_AXIS));
    scrollPaneLeft.setViewportView(labelPanel);

    add(scrollPaneLeft);

    jPanel1.setMaximumSize(new java.awt.Dimension(10, 5000));
    jPanel1.setMinimumSize(new java.awt.Dimension(10, 300));
    jPanel1.setName(""); // NOI18N
    jPanel1.setPreferredSize(new java.awt.Dimension(10, 300));
    add(jPanel1);

    scrollPane2.setBorder(null);

    textFieldPanel.setLayout(new javax.swing.BoxLayout(textFieldPanel, javax.swing.BoxLayout.PAGE_AXIS));
    scrollPane2.setViewportView(textFieldPanel);

    add(scrollPane2);
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel labelPanel;
  private javax.swing.JScrollPane scrollPane2;
  private javax.swing.JScrollPane scrollPaneLeft;
  private javax.swing.JPanel textFieldPanel;
  // End of variables declaration//GEN-END:variables

	void addCostCategory(Category cc) {
		String categoryName = cc.getIdentifier();
		JLabel lb = new JLabel(categoryName);
//		lb.setPreferredSize(new Dimension(200, 20));
		lb.setMaximumSize(new Dimension(200, 20));
		lb.setHorizontalAlignment(SwingConstants.RIGHT);

		JTextField tf = new JTextField();
		tf.setName(categoryName);
		tf.setPreferredSize(new Dimension(130, 20));
		tf.setMaximumSize(new Dimension(130, 20));

		costCategoryTFs.add(tf);
		labelPanel.add(lb);
		labelPanel.add(Box.createRigidArea(new Dimension(0,10)));
		textFieldPanel.add(tf);
		textFieldPanel.add(Box.createRigidArea(new Dimension(0,10)));
	}

	void addTimeCategory(Category tc) {
		String categoryName = tc.getIdentifier();
		JLabel lb = new JLabel(categoryName);
//		lb.setPreferredSize(new Dimension(200, 20));
		lb.setMaximumSize(new Dimension(200, 20));
		lb.setHorizontalAlignment(SwingConstants.RIGHT);

		JTextField tf = new JTextField();
		tf.setName(categoryName);
		tf.setPreferredSize(new Dimension(130, 20));
		tf.setMaximumSize(new Dimension(130, 20));

		timeCategoryTFs.add(tf);
		labelPanel.add(lb);
		labelPanel.add(Box.createRigidArea(new Dimension(0,10)));
		textFieldPanel.add(tf);
		textFieldPanel.add(Box.createRigidArea(new Dimension(0,10)));
	}

}
