/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.sofa.limo.view.graphs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.function.Consumer;
import javafx.scene.chart.BarChart;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import javafx.scene.chart.Chart;
import javafx.scene.chart.PieChart;
import nl.fontys.sofa.limo.view.topcomponent.ResultTopComponent;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.Utilities;
import org.openide.windows.Mode;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@TopComponent.Description(
        preferredID = "GraphSwitchTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "nl.fontys.sofa.limo.view.graphs.GraphSwitchTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GraphSwitchAction"//,
//        preferredID = "GraphSwitchTopComponent"
)
@Messages({
    "CTL_GraphSwitchAction=GraphSwitch",
    "CTL_GraphSwitchTopComponent=GraphSwitch Window",
    "HINT_GraphSwitchTopComponent=This is a GraphSwitch window"
})
public final class GraphSwitchTopComponent extends TopComponent implements LookupListener {

    private Lookup.Result<ResultTopComponent.GraphChangeListener> result = null;

    public GraphSwitchTopComponent() {
        initComponents();
        setName(Bundle.CTL_GraphSwitchTopComponent());
        setToolTipText(Bundle.HINT_GraphSwitchTopComponent());
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);

        result = Utilities.actionsGlobalContext().lookupResult(ResultTopComponent.GraphChangeListener.class);
        result.addLookupListener(this);
        Mode findMode = WindowManager.getDefault().findMode("editor");

    }

    private Class<? extends Chart> chartClass;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieSelect = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        org.openide.awt.Mnemonics.setLocalizedText(pieSelect, org.openide.util.NbBundle.getMessage(GraphSwitchTopComponent.class, "GraphSwitchTopComponent.text")); // NOI18N
        pieSelect.setName(""); // NOI18N
        pieSelect.setOpaque(false);
        pieSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieSelectActionPerformed(evt);
            }
        });
        add(pieSelect);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(GraphSwitchTopComponent.class, "GraphSwitchTopComponent.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (chartClass != BarChart.class) {
            chartClass = BarChart.class;
            notifyGraphTypeChangeListener();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pieSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieSelectActionPerformed
        if (chartClass != PieChart.class) {
            chartClass = PieChart.class;
            notifyGraphTypeChangeListener();
        }
    }//GEN-LAST:event_pieSelectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton pieSelect;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    ResultTopComponent.GraphChangeListener graphTypeChangeListener = null;

    private void notifyGraphTypeChangeListener() {

        ActionEvent event = new ActionEvent(chartClass, ActionEvent.ACTION_FIRST, "Chart class changed");
        graphTypeChangeListener.actionPerformed(event);
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    @Override
    public void resultChanged(LookupEvent le) {

        Collection<? extends ResultTopComponent.GraphChangeListener> allInstances = result.allInstances();
        if (!allInstances.isEmpty()) {
            WindowManager.getDefault().findMode("properties").dockInto(this);
            this.open();
            this.requestVisible();
            graphTypeChangeListener = allInstances.iterator().next();
        } else {
            WindowManager winMan = WindowManager.getDefault();
            List<TopComponent> openComponents = new ArrayList();
            winMan.getModes().parallelStream().forEach(n -> {
                List<TopComponent> open = new ArrayList<>();
                Collections.addAll(open, winMan.getOpenedTopComponents(n));
                open.parallelStream().filter(t -> t instanceof ResultTopComponent).forEach(o -> openComponents.add(o));
            });
            if (openComponents.isEmpty()) {
                this.close();
            }
        }

    }

}
