/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.sofa.limo.view.wizard.hub;

import java.util.ArrayList;
import javax.swing.JPanel;
import nl.fontys.sofa.limo.domain.location.Continents;
import nl.fontys.sofa.limo.domain.location.CountryCode;
import nl.fontys.sofa.limo.domain.location.Location;

public final class HubVisualPanel3 extends JPanel {

    /**
     * Creates new form HubVisualPanel3
     */
    public HubVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Set Location";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblContinent = new javax.swing.JLabel();
        tfStreet = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        tfState = new javax.swing.JTextField();
        cmbCountry = new javax.swing.JComboBox();
        cmbContinent = new javax.swing.JComboBox();
        lblNumber = new javax.swing.JLabel();
        lblZip = new javax.swing.JLabel();
        tfNumber = new javax.swing.JTextField();
        tfZip = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(lblStreet, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblStreet.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCity, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblCity.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblState, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblState.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblCountry, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblCountry.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblContinent, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblContinent.text")); // NOI18N

        tfStreet.setText(org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.tfStreet.text")); // NOI18N
        tfStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStreetActionPerformed(evt);
            }
        });

        tfCity.setText(org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.tfCity.text")); // NOI18N

        tfState.setText(org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.tfState.text")); // NOI18N
        
        ArrayList<CountryCode> countryCodeList = new ArrayList<CountryCode>();
        for(CountryCode countryCode :CountryCode.values()){
            countryCodeList.add(countryCode);
        }

      
        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(countryCodeList.toArray()));

        cmbContinent.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        org.openide.awt.Mnemonics.setLocalizedText(lblNumber, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblNumber.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblZip, org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.lblZip.text")); // NOI18N

        tfNumber.setText(org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.tfNumber.text")); // NOI18N

        tfZip.setText(org.openide.util.NbBundle.getMessage(HubVisualPanel3.class, "HubVisualPanel3.tfZip.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblContinent)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbContinent, 0, 202, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblState)
                                                .addComponent(lblCountry)
                                                .addComponent(lblCity)
                                                .addComponent(lblStreet))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(tfState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                                .addComponent(tfCity, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(tfStreet, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lblNumber)
                                                                .addComponent(lblZip)))
                                                .addComponent(cmbCountry, 0, 202, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfNumber)
                                .addComponent(tfZip, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblStreet)
                                .addComponent(tfStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNumber)
                                .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCity)
                                .addComponent(tfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblZip)
                                .addComponent(tfZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblState)
                                .addComponent(tfState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCountry)
                                .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblContinent)
                                .addComponent(cmbContinent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>    

    public Location getHubLocation() {
        location = new Location((Continents) cmbContinent.getSelectedItem());
        
        if(!tfStreet.getText().isEmpty()){
            location.setStreet(tfState.getText());
        }
        if(!tfNumber.getText().isEmpty()){
            location.setHousenumber(tfNumber.getText());
        }
        if(!tfCity.getText().isEmpty()){
            location.setTown(tfCity.getText());
        }
        if(!tfZip.getText().isEmpty()){
            location.setPostcode(tfZip.getText());
        }
        if(!tfState.getText().isEmpty()){
            location.setState(tfState.getText());
        }

        if(cmbCountry.getSelectedIndex()!=0){
            location.setCountry((CountryCode) cmbCountry.getSelectedItem());
        }
        
        return location;
    }

    private void tfStreetActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private javax.swing.JComboBox cmbContinent;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContinent;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblZip;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfState;
    private javax.swing.JTextField tfStreet;
    private javax.swing.JTextField tfZip;
    private Location location;
}
