/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.sofa.limo.view;

import java.awt.BorderLayout;
import nl.fontys.sofa.limo.view.factory.HubTypeChildFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
		dtd = "-//nl.fontys.sofa.limo.view//HubType//EN",
		autostore = false
)
@TopComponent.Description(
		preferredID = "HubTypeTopComponent",
		//iconBase="SET/PATH/TO/ICON/HERE", 
		persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "nl.fontys.sofa.limo.view.HubTypeTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
		displayName = "#CTL_HubTypeAction",
		preferredID = "HubTypeTopComponent"
)
@Messages({
	"CTL_HubTypeAction=HubType",
	"CTL_HubTypeTopComponent=HubType Window",
	"HINT_HubTypeTopComponent=This is a HubType window"
})
public final class HubTypeTopComponent extends TopComponent
		implements ExplorerManager.Provider{
	private final ExplorerManager em = new ExplorerManager();

	public HubTypeTopComponent() {
		initComponents();
		setName(Bundle.CTL_HubTypeTopComponent());
		setToolTipText(Bundle.HINT_HubTypeTopComponent());
		setLayout(new BorderLayout());

		OutlineView ov = new OutlineView("Hubtypes");
		ov.setPropertyColumns("description", "Description");
		ov.getOutline().setRootVisible(false);
		add(ov, BorderLayout.CENTER);

		Children hubTypechildren = Children.create(new HubTypeChildFactory(), true);
		Node rootNode = new AbstractNode(hubTypechildren);
		rootNode.setDisplayName("Hubtypes");

		em.setRootContext(rootNode);
	}

	@Override
	public ExplorerManager getExplorerManager() {
		return em;
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}

}
