/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.sofa.limo.view;

import java.awt.BorderLayout;
import nl.fontys.sofa.limo.view.factory.LegTypeChildFactory;
import nl.fontys.sofa.limo.view.node.LegTypeRootNode;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays the leg types.
 */
@ConvertAsProperties(
		dtd = "-//nl.fontys.sofa.limo.view//LegType//EN",
		autostore = false
)
@TopComponent.Description(
		preferredID = "LegTypeTopComponent",
		//iconBase="SET/PATH/TO/ICON/HERE", 
		persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "nl.fontys.sofa.limo.view.LegTypeTopComponent")
@ActionReference(path = "Menu/Data" , position = 20 )
@TopComponent.OpenActionRegistration(
		displayName = "#CTL_LegTypeAction",
		preferredID = "LegTypeTopComponent"
)
@Messages({
	"CTL_LegTypeAction=LegType",
	"CTL_LegTypeTopComponent=LegType",
	"HINT_LegTypeTopComponent=Manage Leg Types"
})
public final class LegTypeTopComponent extends TopComponent 
			implements ExplorerManager.Provider{
	private final ExplorerManager em = new ExplorerManager();

	public LegTypeTopComponent() {
		initComponents();
		setName(Bundle.CTL_LegTypeTopComponent());
		setToolTipText(Bundle.HINT_LegTypeTopComponent());
		setLayout(new BorderLayout());

		OutlineView ov = new OutlineView("Legtypes");
		ov.setPropertyColumns("description", "Description");
		ov.getOutline().setRootVisible(false);
		add(ov, BorderLayout.CENTER);

		Children legTypeChildren = Children.create(new LegTypeChildFactory(), true);
		Node rootNode = new LegTypeRootNode(legTypeChildren);
		rootNode.setDisplayName("Legtypes");

		em.setRootContext(rootNode);
		associateLookup(ExplorerUtils.createLookup(em, getActionMap()));
	}

	@Override
	public ExplorerManager getExplorerManager() {
		return em;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}

}
