/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.sofa.limo.view.custom.panel;

import java.awt.Component;
import nl.fontys.sofa.limo.view.action.SimulateAction;

/**
 *
 * @author d3vil
 */
public class ChainToolbar extends javax.swing.JToolBar {

    /**
     * Creates new form ChainToolbar
     */
    public ChainToolbar() {
        initComponents();
        Component toolbarPresenter = new SimulateAction().getToolbarPresenter();
        add(toolbarPresenter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
