package nl.fontys.sofa.limo.view.wizard.hubtype;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JPanel;
import nl.fontys.sofa.limo.api.service.provider.HubTypeService;
import nl.fontys.sofa.limo.domain.component.type.HubType;
import org.openide.util.Lookup;

public final class NewOrDuplicatedHubTypePanel extends JPanel {

    private List<HubType> ht;
    private final ResourceBundle bundle;

    public NewOrDuplicatedHubTypePanel() {
        bundle = ResourceBundle.getBundle("nl/fontys/sofa/limo/view/Bundle");
        initComponents();
    }

    @Override
    public String getName() {
        return bundle.getString("HUB_TYPE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        rbFromScratch = new javax.swing.JRadioButton();
        rbCopyFrom = new javax.swing.JRadioButton();
        cmbHubType = new javax.swing.JComboBox();

        setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.HORIZONTAL;
        c.weightx = 1;
        c.gridx = 0;
        c.gridy = 0;
        buttonGroup1.add(rbFromScratch);
        rbFromScratch.setText(bundle.getString("FROM_SCRATCH"));
        add(rbFromScratch, c);
        rbFromScratch.setSelected(true);

        rbFromScratch.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (rbFromScratch.isSelected()) {
                    cmbHubType.setEnabled(false);
                }
            }
        });

        buttonGroup1.add(rbCopyFrom);
        rbCopyFrom.setText(bundle.getString("COPY_HUBTYPE"));
        c.weightx = 1;
        c.gridx = 0;
        c.gridy = 1;
        add(rbCopyFrom, c);

        rbCopyFrom.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (rbCopyFrom.isSelected()) {
                    cmbHubType.setEnabled(true);
                }
            }
        });

        HubTypeService hubTypeService = Lookup.getDefault().lookup(HubTypeService.class);
        ht = hubTypeService.findAll();
        List<String> hubTypeList = new ArrayList<>();
        for (HubType ht2 : ht) {
            hubTypeList.add(ht2.getName());
        }

        cmbHubType.setModel(new javax.swing.DefaultComboBoxModel(hubTypeList.toArray()));
        c.weightx = 1;
        c.gridx = 0;
        c.gridy = 2;
        add(cmbHubType, c);
        cmbHubType.setEnabled(false);

    }

    public HubType getHubType() {
        if (rbCopyFrom.isSelected()) {
            return ht.get(cmbHubType.getSelectedIndex());
        } else {
            return null;
        }
    }

    javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JRadioButton rbFromScratch;
    javax.swing.JRadioButton rbCopyFrom;
    javax.swing.JComboBox cmbHubType;

}
