package nl.fontys.sofa.limo.view.custom.panel;

import java.awt.Component;
import java.text.NumberFormat;
import javax.swing.JFormattedTextField;
import javax.swing.text.NumberFormatter;
import nl.fontys.sofa.limo.view.action.SimulateAction;

/**
 *
 * @author d3vil
 */
public class ChainToolbar extends javax.swing.JToolBar {

    private SimulateAction simulateAction;
    int numberOfSimulationRuns;

    /**
     * Creates new form ChainToolbar
     */
    public ChainToolbar() {
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents() {

        NumberFormat format = NumberFormat.getIntegerInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        JFormattedTextField inputRunsTF = new JFormattedTextField(formatter);
        simulateAction = new SimulateAction(inputRunsTF);

        Component toolbarPresenter = simulateAction.getToolbarPresenter();

        add(toolbarPresenter);
        add(inputRunsTF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
