/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nl.fontys.limo.view;

import java.awt.BorderLayout;
import nl.fontys.limo.view.factory.CostCategoryFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.OutlineView;
import org.openide.nodes.AbstractNode;
import org.openide.nodes.Children;
import org.openide.nodes.Node;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
				dtd = "-//nl.fontys.limo.view//Category//EN",
				autostore = false
)
@TopComponent.Description(
				preferredID = "CategoryTopComponent",
				//iconBase="SET/PATH/TO/ICON/HERE", 
				persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "nl.fontys.limo.view.CategoryTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
				displayName = "#CTL_CategoryAction",
				preferredID = "CategoryTopComponent"
)
@Messages({
	"CTL_CategoryAction=Category",
	"CTL_CategoryTopComponent=Category Overview",
	"HINT_CategoryTopComponent=Manage your categories"
})
public final class CategoryTopComponent extends TopComponent implements 
				ExplorerManager.Provider{
	private final ExplorerManager em;

	public CategoryTopComponent() {
		initComponents();
		setName(Bundle.CTL_CategoryTopComponent());
		setToolTipText(Bundle.HINT_CategoryTopComponent());
		em = new ExplorerManager();
		em.getRootContext().setDisplayName("Cost and Time Categories");
		setName(Bundle.CTL_CategoryTopComponent());
		setToolTipText(Bundle.HINT_CategoryTopComponent());
		OutlineView ov = new OutlineView("Categories");
		ov.setPropertyColumns("identifier", "Name");
		ov.getOutline().setRootVisible(false);
//		add(new IconView(), BorderLayout.EAST);
		add(ov, BorderLayout.CENTER);
		Children costCategoryChildren = Children.create(new CostCategoryFactory(), true);
		Node rootNode = new AbstractNode(costCategoryChildren);
		rootNode.setDisplayName("Category");
		em.setRootContext(rootNode);
	}

	@Override
	public ExplorerManager getExplorerManager() {
		return em;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.BorderLayout());
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
	@Override
	public void componentOpened() {
		// TODO add custom code on component opening
	}

	@Override
	public void componentClosed() {
		// TODO add custom code on component closing
	}

	void writeProperties(java.util.Properties p) {
		// better to version settings since initial version as advocated at
		// http://wiki.apidesign.org/wiki/PropertyFiles
		p.setProperty("version", "1.0");
		// TODO store your settings
	}

	void readProperties(java.util.Properties p) {
		String version = p.getProperty("version");
		// TODO read your settings according to their version
	}

}
